import {
  AudioLines,
  ChartNoAxesCombined,
  Database,
  ArrowLeftRight,
  Sparkles,
  Workflow,
} from "lucide-react";
export const apps = [
  {
    id: "whiteboard",
    name: "White Board Clean Up",
    description: "Clearer whiteboards and paper notes",
    icon: Sparkles,
    route: "/whiteboard",
    status: "active",
    theme: "blue",
  },
  {
    id: "lumo",
    name: "Lumo",
    description: "Meeting Assistant",
    tagline: "Listen • Capture • Act",
    icon: AudioLines,
    route: "/lumo",
    status: "active",
    theme: "orange",
  },
  {
    id: "data",
    name: "Data Tools",
    description: "Clarity from complexity",
    icon: Database,
    route: "/data",
    status: "coming-soon",
    theme: "blue",
  },
  {
    id: "handover",
    name: "Handover",
    description: "Keep your team in sync",
    icon: ArrowLeftRight,
    route: "/handover",
    status: "coming-soon",
    theme: "green",
  },
  {
    id: "reporting",
    name: "Reporting",
    description: "The bigger picture",
    icon: ChartNoAxesCombined,
    route: "/reporting",
    status: "coming-soon",
    theme: "purple",
  },
  {
    id: "assistant",
    name: "AI Assistant",
    description: "A little extra intelligence",
    icon: Sparkles,
    route: "/assistant",
    status: "coming-soon",
    theme: "pink",
  },
  {
    id: "spotfire",
    name: "Spotfire Assistant",
    description: "Insights, connected",
    icon: Workflow,
    route: "/spotfire",
    status: "coming-soon",
    theme: "cyan",
  },
] as const;
